[server]
enableStaticServing = true

[theme]
primaryColor = "#2483E2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#F8F8F7"
sidebarSecondaryBackgroundColor = "#ffffff"
textColor = "#37352f"
linkColor = "#73716E"
borderColor = "#D9D9D9"
showBorderAroundInputs = true
roundness = 0.25
font = 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI Variable Display", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol"'

