[server]
enableStaticServing = true

[theme]
# Notion
# What's missing/doesn't look great:
# - code background is not visible, would want #F7F6F3
# - hover color on selectbox etc is not visible, would want #f3f3f3
# - active page background should be #F0F0EF
# - colored text and callouts should be adapted to Notion colors (uses black text by default!)
# - adapting font sizes of header levels would be nice (weights are actually the same!)
primaryColor = "#2483E2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
sidebarBackgroundColor = "#F8F8F7"
sidebarSecondaryBackgroundColor = "#ffffff"
textColor = "#37352f"
linkColor = "#73716E"
borderColor = "#D9D9D9"
showBorderAroundInputs = true
roundness = 0.25
font = 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI Variable Display", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol"'

